[2024-09-11T11:54:41.901+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-09-11T11:54:41.928+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cryptocurrencies_etl.run_pipeline_task manual__2024-09-11T11:54:40.221424+00:00 [queued]>
[2024-09-11T11:54:41.937+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cryptocurrencies_etl.run_pipeline_task manual__2024-09-11T11:54:40.221424+00:00 [queued]>
[2024-09-11T11:54:41.937+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-09-11T11:54:42.141+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_pipeline_task> on 2024-09-11 11:54:40.221424+00:00
[2024-09-11T11:54:42.151+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=66) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-11T11:54:42.153+0000] {standard_task_runner.py:63} INFO - Started process 68 to run task
[2024-09-11T11:54:42.157+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'cryptocurrencies_etl', 'run_pipeline_task', 'manual__2024-09-11T11:54:40.221424+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dag_etl.py', '--cfg-path', '/tmp/tmp8yna9l1y']
[2024-09-11T11:54:42.159+0000] {standard_task_runner.py:91} INFO - Job 12: Subtask run_pipeline_task
[2024-09-11T11:54:42.216+0000] {task_command.py:426} INFO - Running <TaskInstance: cryptocurrencies_etl.run_pipeline_task manual__2024-09-11T11:54:40.221424+00:00 [running]> on host e90ab63fed78
[2024-09-11T11:54:42.327+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cryptocurrencies_etl' AIRFLOW_CTX_TASK_ID='run_pipeline_task' AIRFLOW_CTX_EXECUTION_DATE='2024-09-11T11:54:40.221424+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-11T11:54:40.221424+00:00'
[2024-09-11T11:54:42.328+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-09-11T11:54:42.345+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-09-11T11:54:42.346+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dag_etl.py", line 42, in execute_pipeline_task
    return run_pipeline()
           ^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/crypto_data.py", line 15, in run_pipeline
    data = fetch_crypto_data()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/getData.py", line 27, in fetch_crypto_data
    session = Session()
              ^^^^^^^
NameError: name 'Session' is not defined
[2024-09-11T11:54:42.358+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=cryptocurrencies_etl, task_id=run_pipeline_task, run_id=manual__2024-09-11T11:54:40.221424+00:00, execution_date=20240911T115440, start_date=20240911T115441, end_date=20240911T115442
[2024-09-11T11:54:42.375+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 12 for task run_pipeline_task (name 'Session' is not defined; 68)
[2024-09-11T11:54:42.394+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-09-11T11:54:42.409+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
